### ISSUE TITLE
Make Poison an optional dependency

### ISSUE THREAD

**Issue by mgwidmann** [JakeStaTeresa/Currencies#1]
You should be able to mark poison as an optional dependency in your mix.exs, and then in all places that reference `Poison`, simply check if poison is available. Heres how to do it:
https://elixirforum.com/t/how-to-check-if-a-module-exists-how-to-check-if-a-module-has-a-function/581

**Comment by JakeStaTeresa** [comment]
@mgwidmann this has been addressed in the above changeset. I've added a mix task to perform json to binary conversion of the currency data files. At runtime the binary is the only one loaded.
